print('Mercado de Dicas')
print('----------------------------------------')
print('1. Cor da bandeira  - custa 4 tentativas')
print('2. Letra da capital - custa 3 tentativas')
print('3. Área             - custa 6 tentativas')
print('4. População        - custa 5 tentativas')
print('5. Continente       - custa 7 tentativas')
print('0. Sem dica')
print('----------------------------------------')
opcao_dica = input('Escolha sua opção [0|1|2|3|4]:')